import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from 'next/link';
import About from './about';


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Car Tracking App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="bg-gray-800 flex items-center justify-between px-4 py-3">
  <div className="flex items-center">
    <Link href="/">
      <img src="/logo.png" alt="Car Tracking App logo" className="h-8" />
    </Link>
  </div>
  <div className="flex items-center space-x-4">
    <Link href="/" className="text-gray-300 hover:text-white">Home</Link>
    <Link href="/about" className="text-gray-300 hover:text-white">About </Link>
    <Link href="/how-it-works" className="text-gray-300 hover:text-white">How it works</Link>
    <Link href="/contact" className="text-gray-300 hover:text-white">Contact Us</Link>
  </div>
  <div className="flex items-center">
    <Link href="/login" className="btn btn-white mr-4">Log In</Link>
    <Link href="/signup" className="btn btn-blue">Sign Up</Link>
  </div>
</nav>

      <main className="flex flex-col items-center justify-center p-6">
  <h1 className="text-3xl font-bold text-center">Welcome to the Car Tracking App!</h1>
  <p className="text-center p-2">This app allows you to track your cars location, set reminders for maintenance, and more.</p>
  <div className="flex justify-center mt-4">
    <a href="/track" className="px-4 py-2 font-bold text-white bg-blue-500 rounded-full hover:bg-blue-700 focus:outline-none focus:shadow-outline-blue active:bg-blue-800">
      Track Your Car
    </a>
  </div>
</main>

    </>
  );
}
